# backend/app/api/embedding_service.py

import os
import logging
from typing import List, Union
import numpy as np

logger = logging.getLogger(__name__)

try:
    from sentence_transformers import SentenceTransformer
    SENTENCE_TRANSFORMERS_AVAILABLE = True
except Exception as e:
    # Catch all exceptions (ImportError, RuntimeError, etc.) to prevent backend crash
    SENTENCE_TRANSFORMERS_AVAILABLE = False
    logger.warning(f"sentence-transformers not available ({type(e).__name__}: {e}). Semantic search will be disabled.")

class EmbeddingService:
    """
    Service for generating text embeddings for semantic search.
    Uses sentence-transformers to convert text to vector embeddings.
    """
    
    def __init__(self, model_name: str = None):
        """
        Initialize embedding service with a sentence transformer model.
        
        Args:
            model_name: Name of the model to use. Defaults to 'all-MiniLM-L6-v2' (384 dims, fast)
                       Options: 'all-MiniLM-L6-v2' (384d), 'all-mpnet-base-v2' (768d)
        """
        self.model = None
        self.model_name = model_name or os.getenv("EMBEDDING_MODEL", "all-MiniLM-L6-v2")
        self.embedding_dim = 384  # Default for all-MiniLM-L6-v2
        
        if not SENTENCE_TRANSFORMERS_AVAILABLE:
            logger.error("sentence-transformers not available. Install with: pip install sentence-transformers")
            return
        
        try:
            logger.info(f"Loading embedding model: {self.model_name}")
            self.model = SentenceTransformer(self.model_name)
            
            # Set embedding dimension based on model
            if "mpnet" in self.model_name.lower():
                self.embedding_dim = 768
            elif "MiniLM" in self.model_name:
                self.embedding_dim = 384
            else:
                # Test to get actual dimension
                test_embedding = self.model.encode("test", convert_to_numpy=True)
                self.embedding_dim = len(test_embedding)
            
            logger.info(f"Embedding model loaded. Dimension: {self.embedding_dim}")
        except Exception as e:
            logger.error(f"Failed to load embedding model: {e}")
            self.model = None
    
    def is_available(self) -> bool:
        """Check if embedding service is available"""
        return self.model is not None and SENTENCE_TRANSFORMERS_AVAILABLE
    
    def generate_embedding(self, text: str) -> List[float]:
        """
        Generate embedding for a single text.
        
        Args:
            text: Input text to generate embedding for
            
        Returns:
            List of floats representing the embedding vector
        """
        if not self.is_available():
            logger.warning("Embedding service not available. Returning empty embedding.")
            return [0.0] * self.embedding_dim
        
        if not text or not text.strip():
            return [0.0] * self.embedding_dim
        
        try:
            embedding = self.model.encode(text, convert_to_numpy=True, normalize_embeddings=True)
            return embedding.tolist()
        except Exception as e:
            logger.error(f"Failed to generate embedding: {e}")
            return [0.0] * self.embedding_dim
    
    def generate_embeddings_batch(self, texts: List[str], batch_size: int = 32) -> List[List[float]]:
        """
        Generate embeddings for multiple texts (more efficient than individual calls).
        
        Args:
            texts: List of input texts
            batch_size: Batch size for processing
            
        Returns:
            List of embedding vectors
        """
        if not self.is_available():
            logger.warning("Embedding service not available. Returning empty embeddings.")
            return [[0.0] * self.embedding_dim] * len(texts)
        
        if not texts:
            return []
        
        # Filter out empty texts
        valid_texts = [t if t and t.strip() else " " for t in texts]
        
        try:
            embeddings = self.model.encode(
                valid_texts,
                convert_to_numpy=True,
                normalize_embeddings=True,
                batch_size=batch_size,
                show_progress_bar=False
            )
            return embeddings.tolist()
        except Exception as e:
            logger.error(f"Failed to generate batch embeddings: {e}")
            return [[0.0] * self.embedding_dim] * len(texts)
    
    def get_embedding_dimension(self) -> int:
        """Get the dimension of embeddings generated by this model"""
        return self.embedding_dim

# Global instance (lazy-loaded)
_embedding_service = None

def get_embedding_service() -> EmbeddingService:
    """Get or create global embedding service instance"""
    global _embedding_service
    if _embedding_service is None:
        _embedding_service = EmbeddingService()
    return _embedding_service

